# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "uas" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-f0ab8aad-bc4a-4343-a178-107b67313029";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-f0ab8aad-bc4a-4343-a178-107b67313029".device = "/dev/disk/by-uuid/f0ab8aad-bc4a-4343-a178-107b67313029";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/12A8-3D77";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/mapper/luks-61d676d2-6e31-41cd-a953-13d2bf0fd257";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
