# Import this module only after hardware-configuration.nix contains the real
# swap partition generated by the Framework installer.
{
  config,
  lib,
  ...
}: let
  swaps = config.swapDevices;
  swap =
    if builtins.length swaps == 1
    then builtins.head swaps
    else null;
in {
  assertions = [
    {
      assertion =
        swap
        != null
        && swap ? device
        && lib.hasPrefix "/dev/" swap.device;
      message = ''
        Theseus hibernation requires exactly one partition-backed swap device
        in hosts/Theseus/hardware-configuration.nix (currently
        /dev/disk/by-uuid/c42d065c-1419-42c6-b230-c46632922e7f). Confirm that
        UUID on-box before activate. Swap files additionally require a resume
        offset and are intentionally rejected.
      '';
    }
  ];

  boot.resumeDevice = lib.mkIf (swap != null) swap.device;

  systemd.sleep.settings.Sleep = {
    AllowSuspendThenHibernate = true;
    HibernateDelaySec = "2h";
  };

  services.logind.settings.Login = {
    HandleLidSwitch = lib.mkForce "suspend-then-hibernate";
    HandleLidSwitchExternalPower = lib.mkForce "suspend-then-hibernate";
  };
}
